const products = [
    {
        id: 1,
        name: "HAVIT HV-G92 Gamepad", 
        rating: 5,
        numberRating: 88,
        stock: 99,
        price: 160,
        discountPrice: 120,
        discountRate: "-40%",
        description: "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
        color: [gray, red],
        size: [],
        img: "./images/products/Frame 611.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 3,
        name: "IPS LCD Gaming Monitor", 
        rating: 5,
        numberRating: 99,
        stock: 99,
        price: 400,
        discountPrice: 370,
        discountRate: "-30%",
        description: "Ultra-Wide Gaming Monitor High-resolution display with ultra-wide aspect ratio. Features rapid refresh rate and adaptive sync technology for smooth, immersive gameplay without motion blur.",
        color: [],
        size: [],
        img: "./images/products/Frame 613.png"
    },
    {
        id: 4,
        name: "S-Series Comfort Chair", 
        rating: 4.5,
        numberRating: 99,
        stock: 99,
        price: 400,
        discountPrice: 375,
        discountRate: "-25%",
        description: "Ergonomic Comfort Chair Premium quality materials with adjustable lumbar support and recline features. Provides maximum comfort for long hours of sitting with breathable mesh fabric.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 5,
        name: "The North Coat", 
        rating: 5,
        numberRating: 65,
        stock: 99,
        price: 360,
        discountPrice: 260,
        discountRate: "-40%",
        description: "Winter North Coat High-quality insulation with water-resistant exterior. Features multiple pockets, adjustable hood, and thermal lining for ultimate warmth & protection in cold climates.",
        color: [],
        size: [],
        img: "./images/products/Frame 605.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 1,
        name: "HAVIT HV-G92 Gamepad", 
        rating: 5,
        numberRating: 88,
        stock: 99,
        price: 160,
        discountPrice: 120,
        discountRate: "-40%",
        description: "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
        color: [gray, red],
        size: [],
        img: "./images/products/Frame 611.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 1,
        name: "HAVIT HV-G92 Gamepad", 
        rating: 5,
        numberRating: 88,
        stock: 99,
        price: 160,
        discountPrice: 120,
        discountRate: "-40%",
        description: "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
        color: [gray, red],
        size: [],
        img: "./images/products/Frame 611.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    },
    {
        id: 2,
        name: "AK-900 Wired Keyboard", 
        rating: 4.5,
        numberRating: 75,
        stock: 99,
        price: 1160,
        discountPrice: 960,
        discountRate: "-35%",
        description: "LED Backlit Gaming Keyboard High-quality mechanical switches with customizable RGB lighting. Durable design with anti-ghosting keys for precise control & comfortable typing experience.",
        color: [],
        size: [],
        img: "./images/products/Frame 612 copy.png"
    }
];